components:
  llm:
    init_parameters:
      generation_kwargs: {}
      model: mistral
      raw: false
      streaming_callback: null
      system_prompt: null
      template: null
      timeout: 120
      url: http://localhost:11434/api/generate
    type: haystack_integrations.components.generators.ollama.generator.OllamaGenerator
  prompt_builder:
    init_parameters:
      template: "\n    Given these documents, answer the question.\nDocuments:\n \
        \   {% for doc in documents %}\n        {{ doc.content }}\n    {% endfor %}\n\
        \n    \nQuestion: {{question}}\n    \nAnswer:\n    "
    type: haystack.components.builders.prompt_builder.PromptBuilder
  retriever:
    init_parameters:
      certainty: null
      distance: null
      document_store:
        init_parameters:
          additional_config: null
          additional_headers: null
          auth_client_secret: null
          collection_settings:
            class: Default
            invertedIndexConfig:
              indexNullState: true
            properties:
            - dataType:
              - text
              name: _original_id
            - dataType:
              - text
              name: content
            - dataType:
              - text
              name: dataframe
            - dataType:
              - blob
              name: blob_data
            - dataType:
              - text
              name: blob_mime_type
            - dataType:
              - number
              name: score
          embedded_options: null
          proxies: null
          startup_period: 5
          trust_env: false
          url: http://localhost:8080
        type: haystack_integrations.document_stores.weaviate.document_store.WeaviateDocumentStore
      filters: {}
      top_k: 5
    type: haystack_integrations.components.retrievers.weaviate.embedding_retriever.WeaviateEmbeddingRetriever
  text_embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cuda:0
        type: single
      model: sentence-transformers/all-mpnet-base-v2
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        strict: false
        type: env_var
    type: haystack.components.embedders.sentence_transformers_text_embedder.SentenceTransformersTextEmbedder
connections:
- receiver: retriever.query_embedding
  sender: text_embedder.embedding
- receiver: prompt_builder.documents
  sender: retriever.documents
- receiver: llm.prompt
  sender: prompt_builder.prompt
max_loops_allowed: 100
metadata: {}
